name: Docker Compose and NPM Tests

on:
  push:
    branches:
      - main # Trigger on push to main branch (you can change this if needed)
  pull_request:
    branches:
      - main # Trigger on pull request to main branch (you can change this if needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker containers
        run: |
          docker compose up -d --build

  test:
    runs-on: ubuntu-latest
    needs: build # Ensure that the test job runs after the build job completes successfully

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Shut down Docker containers
        run: docker compose down

  deploy:
    runs-on: ubuntu-latest
    needs: test # Ensure that deployment happens only after tests pass
    if: success() # Only run this job if the test job was successful

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install rsync and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync sshpass

      - name: Stop Docker containers on the server
        run: |
          # Stop any running containers on the server before copying new files
          sshpass -p 'eqKE89Vmipob&Q' ssh -o StrictHostKeyChecking=no root@157.230.41.241 "cd project_directory && docker compose down -v"

      - name: Delete existing project files on the server
        run: |
          # Delete the existing project files on the server to ensure a clean deployment
          sshpass -p 'eqKE89Vmipob&Q' ssh -o StrictHostKeyChecking=no root@157.230.41.241 "rm -rf /root/project_directory/*"

      - name: Copy project to server, excluding node_modules and build files
        run: |
          # Use rsync to copy the project to the server, excluding the node_modules folder and build files
          sshpass -p 'eqKE89Vmipob&Q' rsync -avz --exclude='node_modules' --exclude='**/build' -e "ssh -o StrictHostKeyChecking=no" ./ root@157.230.41.241:/root/project_directory

      - name: Run Docker Compose on the server
        run: |
          # Run Docker Compose on the server to start the containers
          sshpass -p 'eqKE89Vmipob&Q' ssh -o StrictHostKeyChecking=no root@157.230.41.241 "cd /root/project_directory && docker compose up -d --build"
