name: Docker Compose and NPM Tests

on:
  push:
    branches:
      - main # Trigger on push to main branch (you can change this if needed)
  pull_request:
    branches:
      - main # Trigger on pull request to main branch (you can change this if needed)

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker containers
        run: |
          docker compose up -d --build

      - name: Install NPM dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Shut down Docker containers
        run: docker compose down

      - name: Copy project to server and run Docker Compose on success
        if: success() # Only run this step if the tests passed
        run: |
          # Install sshpass to enable password authentication
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Copy project to the server using SCP with password authentication
          sshpass -p 'eqKE89Vmipob&Q' scp -r ./ root@157.230.41.241:/root/project_directory

          # Run Docker Compose on the server through SSH with password authentication
          sshpass -p 'eqKE89Vmipob&Q' ssh root@157.230.41.241 "cd /root/project_directory && docker compose down -v && docker compose up -d --build"
